package com.dhcc.zhyl.splider.entity;
// Generated 2017-11-8 20:13:04 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UrlInfo generated by hbm2java
 */
@Entity
@Table(name = "url_info", uniqueConstraints = @UniqueConstraint(columnNames = "url"))
public class UrlInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3194012549586457775L;
	private String id;
	private String url;
	private String title;
	private Date fetchTime;

	public UrlInfo() {
	}

	public UrlInfo(String id) {
		this.id = id;
	}

	public UrlInfo(String id, String url, String title, Date fetchTime) {
		this.id = id;
		this.url = url;
		this.title = title;
		this.fetchTime = fetchTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "url", unique = true)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fetch_time", length = 19)
	public Date getFetchTime() {
		return this.fetchTime;
	}

	public void setFetchTime(Date fetchTime) {
		this.fetchTime = fetchTime;
	}

}
