package com.dhcc.zhyl.splider.entity;
// Generated 2017-11-17 22:23:39 by Hibernate Tools 5.1.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Word generated by hbm2java
 */
@Entity
@Table(name = "word", catalog = "splider")
public class Word implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2051135531723537575L;
	private WordId id;

	public Word() {
	}

	public Word(WordId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "b", column = @Column(name = "b", length = 20)), @AttributeOverride(name = "c", column = @Column(name = "c", length = 20)) })
	public WordId getId() {
		return this.id;
	}

	public void setId(WordId id) {
		this.id = id;
	}

}
